USE STORE
GO

SELECT*
FROM HOADON
WHERE YEAR(NGAYLAP) = '2020'

SELECT*
FROM KHACHHANG
WHERE TPHO = 'TPHCM'

SELECT*
FROM SANPHAM
WHERE GIA < 3000 AND GIA > 500

SELECT*
FROM SANPHAM
WHERE SOLUONGTON < 100

SELECT SANPHAM.TENSP
FROM SANPHAM, CT_HOADON
WHERE SANPHAM.MASP = CT_HOADON.MASP
GROUP BY SANPHAM.MASP , SANPHAM.TENSP
HAVING SUM(CT_HOADON.SOLUONG) >=ALL (SELECT SUM(SOLUONG)
									FROM CT_HOADON
									GROUP BY MASP)

SELECT SANPHAM.TENSP
FROM SANPHAM, CT_HOADON
WHERE SANPHAM.MASP = CT_HOADON.MASP
GROUP BY SANPHAM.MASP , SANPHAM.TENSP
HAVING SUM(CT_HOADON.THANHTIEN) >=ALL (SELECT SUM(THANHTIEN)
									FROM CT_HOADON
									GROUP BY MASP)

CREATE TRIGGER TRG_THANHTIEN ON CT_HOADON AFTER INSERT AS
BEGIN
	SELECT*FROM inserted
	UPDATE CT_HOADON
	SET GIABAN = SANPHAM.GIA
	FROM SANPHAM
	WHERE SANPHAM.MASP = CT_HOADON.MASP
	
	UPDATE CT_HOADON
	SET THANHTIEN = INSERTED.SOLUONG * (CT_HOADON.GIABAN - inserted.GIAGIAM)
	FROM inserted
	WHERE inserted.MASP = CT_HOADON.MASP AND inserted.MAHD = CT_HOADON.MAHD AND CT_HOADON.GIABAN > CT_HOADON.GIAGIAM

	UPDATE HOADON
	SET TONGTIEN = (SELECT SUM(CT_HOADON.THANHTIEN) FROM CT_HOADON WHERE CT_HOADON.THANHTIEN IS NOT NULL AND HOADON.MAHD = CT_HOADON.MAHD )
	FROM CT_HOADON
	WHERE HOADON.MAHD = CT_HOADON.MAHD 
	SELECT*FROM inserted
	SELECT * FROM CT_HOADON
END